
# =================================================================
# Compile options
# =================================================================
compile-options:
  build-debug: true

# =================================================================
# External C++ Libraries
# =================================================================
library-cpp:
  toolchain: true
  utility: true
  opencv: "4.5.2"
  opencv-contrib: true
  eigen: "3.3.9"
  pcl: "1.11.1"
  ceres: "2.0.0"
  gtsam: "4.0.3"
  pangolin: "0.6"
  glfw: "3.3.4"
  glad: true

# =================================================================
# External Python Libraries
# =================================================================
library-python:
  python3: true
  open3d: false
  opencv-python: false
  opencv-contrib-python: false
